FROM python:3.11-slim

WORKDIR /mlflow

RUN pip install mlflow pymysql boto3 mysql-connector-python && \
    mkdir -p /mlflow/mlruns && \
    chmod -R 777 /mlflow

EXPOSE 5000

CMD ["mlflow", "server", \
    "--host", "0.0.0.0", \
    "--port", "5000", \
    "--backend-store-uri", "${MLFLOW_BACKEND_STORE_URI}", \
    "--artifacts-destination", "${MLFLOW_DEFAULT_ARTIFACT_ROOT}", \
    "--serve-artifacts"] 